name: EXP-6 CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run CI step
        run: echo "EXP-6 GitHub Actions CI/CD Successful"